version: '3.9'

services:

  as2-middleware:
    image: 752265468063.dkr.ecr.us-east-1.amazonaws.com/open-as2-middleware
    restart: always
    #command: [bash, -c, "aws configure && ws ecr get-login --region us-east-1 --no-include-email"]
    environment:
      - SPRING_PROFILE=staging
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: /home/ubuntu/OpenAS2Servers/sender/data
        target: /OpenAS2Servers/sender/data
      - type: bind
        source: /home/ubuntu/OpenAS2Servers/middleware-logs
        target: /OpenAS2Servers/middleware-logs
    
volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/OpenAS2Servers/sender/data

